# Generated by Django 4.1.2 on 2022-12-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=255)),
                ('date_published', models.DateField()),
                ('blog_text', models.TextField()),
                ('blog_image', models.ImageField(upload_to='posts_images')),
                ('blog_slug', models.SlugField(blank=True, default=None, null=True, unique=True)),
            ],
        ),
    ]
