# Generated by Django 4.1.2 on 2022-12-04 10:48

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=255, verbose_name='Название')),
                ('date_published', models.DateField(verbose_name='Дата публикации')),
                ('blog_text', tinymce.models.HTMLField(verbose_name='Текст поста')),
                ('blog_image', models.ImageField(help_text='Не более 400х400', upload_to='posts_images', verbose_name='Главная картинка поста')),
                ('slug', models.SlugField(default=None, max_length=400, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
