# Generated by Django 4.1.2 on 2022-12-01 14:26

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_image',
            field=models.ImageField(help_text='Не более 400х400', upload_to='posts_images', verbose_name='Главная картинка поста'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_slug',
            field=models.SlugField(blank=True, default=None, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_text',
            field=tinymce.models.HTMLField(verbose_name='Текст поста'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date_published',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
    ]
