# Generated by Django 4.1.2 on 2022-12-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_userip'),
        ('blog', '0007_blogpost_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='views',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='Users.userip'),
        ),
    ]
