# Generated by Django 4.1.2 on 2022-12-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comments_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='moderate',
            field=models.BooleanField(default=False, verbose_name='Проверен'),
        ),
    ]
