# Generated by Django 4.1.2 on 2022-12-12 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_comments_moderate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date_published',
            field=models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Дата публикации'),
        ),
    ]
