# Generated by Django 4.1.2 on 2022-12-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_comments_date_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='raiting',
        ),
    ]
