# Generated by Django 4.1.2 on 2022-12-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_comments_raiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='server_raiting',
            field=models.IntegerField(default=0),
        ),
    ]
