# Generated by Django 4.1.2 on 2022-12-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_blogpost_server_raiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='server_raiting',
        ),
    ]
