# Generated by Django 4.1.2 on 2022-12-04 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=125, verbose_name='Статус')),
                ('avatar', models.ImageField(upload_to='profile_avatars', verbose_name='Аватар')),
                ('is_gold', models.BooleanField(default=None, verbose_name='GOLD подписчик')),
                ('link', models.SlugField(blank=True, default=None, null=True, unique=True, verbose_name='Ссылка на пользователя')),
                ('test', models.CharField(default=None, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
