# Generated by Django 4.1.2 on 2022-12-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='test',
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_gold',
            field=models.BooleanField(default=None, null=True, verbose_name='GOLD подписчик'),
        ),
    ]
