# Generated by Django 4.1.2 on 2022-12-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_avatars/def_ava.jpeg', null=True, upload_to='profile_avatars', verbose_name='Аватар'),
        ),
    ]
