# Generated by Django 4.1.2 on 2022-12-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_profile_test_alter_profile_is_gold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=None, upload_to='profile_avatars', verbose_name='Аватар'),
        ),
    ]
