# Generated by Django 4.1.2 on 2022-12-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='../static/assets/images/def_ava.jpeg', upload_to='profile_avatars', verbose_name='Аватар'),
        ),
    ]
