# Generated by Django 4.1.2 on 2022-12-08 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0005_subscriber_profile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='Подписчики', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
