# Generated by Django 4.1.2 on 2022-12-18 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l2servers', '0015_alter_gameserver_server_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0006_alter_profile_followers_delete_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='servers',
            field=models.ManyToManyField(blank=True, to='l2servers.gameserver', verbose_name='Сервера пользователя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='Подписчики', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
    ]
