# Generated by Django 4.1.2 on 2022-12-18 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_profile_servers_alter_profile_followers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
    ]
