# Generated by Django 4.1.2 on 2022-12-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_gold',
            field=models.BooleanField(default=False, null=True, verbose_name='GOLD подписчик'),
        ),
    ]
