# Generated by Django 4.1.2 on 2022-12-04 10:48

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Lineage 2', 'Lineage 2'), ('Rust', 'Rust'), ('Minecraft', 'Minecraft'), ('Word Of Warcraft', 'World_of_Warcraft'), ('CS-GO', 'Cs_Go'), ('ARMA 3', 'Arma3'), ('DayZ', 'DayZ'), ('Others', 'Others')], default='Lineage 2', max_length=20)),
                ('game_slug', models.SlugField(blank=True, default=None, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('date_published', models.DateField()),
                ('server_open', models.DateField()),
                ('max_online', models.IntegerField(default=0)),
                ('current_online', models.IntegerField(default=0)),
                ('server_ico', models.ImageField(upload_to='servers_logo')),
                ('server_slug', models.SlugField(blank=True, default=None, null=True, unique=True)),
                ('state', django_fsm.FSMField(choices=[('New', 'New'), ('Open', 'Open')], default='Open', max_length=50)),
                ('online_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Game', to='l2servers.game')),
            ],
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=True)),
                ('vip', models.BooleanField(default=None)),
                ('top_vip', models.BooleanField(default=None)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='l2servers.gameserver')),
            ],
            options={
                'verbose_name': 'Рекламный пост',
                'verbose_name_plural': 'Рекламные посты',
            },
        ),
    ]
