# Generated by Django 4.1.2 on 2022-12-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l2servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameserver',
            name='description',
            field=models.CharField(default='Без описания', max_length=500, verbose_name='Описание сервера'),
        ),
    ]
