# Generated by Django 4.1.2 on 2022-10-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l2servers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='slug',
            new_name='game_slug',
        ),
        migrations.RenameField(
            model_name='gameserver',
            old_name='slug',
            new_name='server_slug',
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(choices=[('Lineage 2', 'Lineage 2'), ('Rust', 'Rust'), ('Minecraft', 'Minecraft'), ('Word Of Warcraft', 'World_of_Warcraft'), ('CS-GO', 'Cs_Go'), ('ARMA 3', 'Arma3'), ('DayZ', 'DayZ'), ('Others', 'Others')], default='Lineage 2', max_length=20),
        ),
    ]
