# Generated by Django 4.1.2 on 2022-12-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l2servers', '0002_gameserver_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameserver',
            old_name='server_ico',
            new_name='server_banner',
        ),
        migrations.RemoveField(
            model_name='gameserver',
            name='current_online',
        ),
        migrations.RemoveField(
            model_name='gameserver',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='gameserver',
            name='max_online',
        ),
        migrations.RemoveField(
            model_name='gameserver',
            name='server_open',
        ),
        migrations.RemoveField(
            model_name='gameserver',
            name='state',
        ),
    ]
