# Generated by Django 4.1.2 on 2022-10-27 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l2servers', '0002_rename_slug_game_game_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameserver',
            name='online_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Game', related_query_name='Games', to='l2servers.game'),
        ),
    ]
