# Generated by Django 4.1.2 on 2022-10-27 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l2servers', '0003_alter_gameserver_online_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameserver',
            name='online_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Game', to='l2servers.game'),
        ),
    ]
