# Generated by Django 4.1.2 on 2022-12-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l2servers', '0003_rename_server_ico_gameserver_server_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameserver',
            name='server_site',
            field=models.URLField(default='l2.ru', max_length=1000),
        ),
    ]
