# Generated by Django 4.1.2 on 2022-12-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l2servers', '0004_gameserver_server_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='gameserver',
            options={'verbose_name': 'Сервер', 'verbose_name_plural': 'Сервера'},
        ),
        migrations.AddField(
            model_name='gameserver',
            name='moderate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gameserver',
            name='server_site',
            field=models.URLField(default='l2.ru', max_length=1000, verbose_name='Ссылка на сервер'),
        ),
    ]
