# Generated by Django 4.1.2 on 2022-10-27 22:20

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('l2servers', '0005_gameserver_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameserver',
            name='state',
            field=django_fsm.FSMField(choices=[('New', 'New'), ('Open', 'Open')], default='Open', max_length=50),
        ),
    ]
