# Generated by Django 4.1.2 on 2022-10-27 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l2servers', '0006_alter_gameserver_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name': 'Рекламный пост', 'verbose_name_plural': 'Рекламные посты'},
        ),
    ]
