# Generated by Django 4.1.2 on 2022-12-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l2servers', '0007_alter_gameserver_online_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameserver',
            name='online_game',
            field=models.CharField(choices=[('lineage-2', 'Lineage 2'), ('Rust', 'Rust'), ('Minecraft', 'Minecraft'), ('Word_of_Warcraft', 'World of Warcraft'), ('csgo', 'Counter-Strike: Global Offensive'), ('arma3', 'ARMA 3'), ('DayZ', 'Day Z'), ('Others', 'Другие')], max_length=40, verbose_name='Игра'),
        ),
    ]
