# Generated by Django 4.1.2 on 2022-12-18 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l2servers', '0008_alter_gameserver_online_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ads',
        ),
    ]
