# Generated by Django 4.1.2 on 2022-12-18 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l2servers', '0012_alter_gameserver_server_ovner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameserver',
            name='server_ovner',
        ),
    ]
