# Generated by Django 4.1.2 on 2022-12-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l2servers', '0015_alter_gameserver_server_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameserver',
            name='server_raiting',
            field=models.IntegerField(default=0),
        ),
    ]
