# Generated by Django 4.1.2 on 2022-12-19 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('l2servers', '0016_gameserver_server_raiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameserver',
            name='server_raiting',
        ),
        migrations.AddField(
            model_name='gameserver',
            name='liked_by',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameserver',
            name='server_owner',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
