# Generated by Django 4.1.2 on 2022-12-19 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('l2servers', '0017_remove_gameserver_server_raiting_gameserver_liked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameserver',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
