# Generated by Django 4.1.2 on 2022-12-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l2servers', '0018_alter_gameserver_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameserver',
            name='server_slug',
            field=models.SlugField(blank=True, default=None, null=True, unique=True, verbose_name='URL'),
        ),
    ]
